# continued

In [2]:



x = [[1,2,3],[4,5,6],[7,1,0]]

In [3]:
ar = np.array(x)

In [4]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [5]:
ar.sum(axis=0)

array([12,  8,  9])

In [6]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [10]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [11]:
ar.T.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [12]:
ar.flat

In [13]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [15]:
ar.ndim

2

In [16]:
ar.size

9

In [17]:
ar.nbytes

36

In [19]:
one = np.array([1,3,4,634,2])

In [20]:
one.argmax()

3

In [21]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [22]:
one.argmin()

0

In [27]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [29]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [30]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [31]:
ar.argmin()

8

In [32]:
ar.argmax()

6

In [33]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [34]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [35]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [36]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [37]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [40]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [41]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [44]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [45]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [46]:
[324, 34] + [34, 543]

[324, 34, 34, 543]

In [47]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [51]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [53]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [54]:
ar.sum()

29

In [55]:
ar.max()

7

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.min()

0

In [58]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [62]:
np.where(ar==5)

(array([1], dtype=int64), array([1], dtype=int64))

In [63]:
type(np.where(ar>5))

tuple

In [64]:
np.where(ar<5)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [65]:
np.count_nonzero(ar)

8

In [66]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [67]:
ar[1,2] = 0

In [68]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [69]:
import sys

In [71]:
py_ar = [0,4,55,2]

In [73]:
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1)* len(py_ar)

112

In [75]:
np_ar.itemsize * np_ar.size

16

In [76]:
np_ar.tolist()

[0, 4, 55, 2]